# Generated by Django 5.1.6 on 2025-03-15 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_idx_product_price'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='idx_product_seller',
        ),
    ]
