services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: django_app
    command: uv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - ./.env

    ports:
      - 8000:8000

    depends_on:
      - db
      - redis

  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  celery:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: celery_worker
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - ./.env

    depends_on:
      - db
      - redis

  smtp4dev:
    image: rnwood/smtp4dev
    container_name: smtp4dev
    ports:
      - 5000:80
    volumes:
      - smtp4dev-data:/smtp4dev
    

volumes:
  postgres_data:
  smtp4dev-data: